# Generated by Codex on 2026-03-20

from django.db import migrations


def set_legacy_team_default(apps, schema_editor):
    User = apps.get_model("authentication", "User")
    User.objects.filter(team__isnull=True).update(team="general")
    User.objects.filter(team="").update(team="general")


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_remove_organization_fk"),
    ]

    operations = [
        migrations.RunPython(set_legacy_team_default, migrations.RunPython.noop),
    ]
